services:
  database:
    image: couturierambroise/my-database:1.0
    build: ./database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - db-network
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  backend:
    image: couturierambroise/my-backend:1.0
    container_name: ${BACKEND_HOST}
    build: ./backend
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      app-network:
      db-network:
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  httpd:
    image: couturierambroise/my-httpd:1.0
    build: ./Server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./front/dist:/usr/local/apache2/htdocs:ro
      - ./Server/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  app-network:
    name: app-network
    external: true
  db-network:
    name: db-network
    external: true

volumes:
  db-data:
    name: db-data
    external: true
